global using Autofac;
global using Avalonia;
global using Avalonia.Controls;
global using Avalonia.Controls.ApplicationLifetimes;
global using Avalonia.Controls.Templates;
global using Avalonia.Interactivity;
global using Avalonia.Media;
global using Avalonia.ReactiveUI;
global using Grpc.Net.Client;
global using MagicOnion.Client;
global using R3;
global using ReactiveUI;
global using System;
global using System.Collections.ObjectModel;
global using System.Reactive.Linq;
global using ReactiveCommand = R3.ReactiveCommand;