global using CHAT_APP.CHAT.INTERFACE;
global using System;
global using System.Linq;
global using System.Threading.Tasks;
global using MagicOnion.Server.Hubs;
global using Microsoft.AspNetCore.Builder;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Server.Kestrel.Core;
global using Microsoft.Extensions.DependencyInjection;